import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const montserrat = localFont({
  src: [
    {
      path: "./fonts/Montserrat-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Montserrat-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/Montserrat-SemiBold.woff2",
      weight: "600",
      style: "semibold",
    },
    {
      path: "./fonts/Montserrat-Bold.woff2",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/Montserrat-ExtraBold.woff2",
      weight: "900",
      style: "extra-bold",
    },
  ],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} font-sans`}>
      <body >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
